### ISSUE TITLE
Missing icons for altcoins in the top 100

### ISSUE THREAD

**Issue by EnterRavement** [atomiclabs/cryptocurrency-icons#104]
Hey, first of all great work and thanks alot for your work. I am planning to use your icons in my project, sadly there were a couple of the Top100 Coins missing. 

The following coins are in the top100 right now and dont have an icon yet:

 Mixin(XIN), WaykiChain(WICC), LOOM Network(LOOM), Cortex(CTXC), Centrality(CENNZ), Matrix Network(MAN), HOLO(HOT), Nexo(NEXO), All Sports(SOC)

If you find time I would be really happy if you would add those, if not thats fine as well, already pretty happy with what you already did, keep it up :)

**Comment by cjdowner** [comment]
You're welcome! 
I'll get these added. CENNZ is already part of the set I believe!

**Comment by sindresorhus** [comment]
@EnterRavement We could use some help finding the logos for these coins. We need a SVG [vector version](https://en.m.wikipedia.org/wiki/Vector_graphics) of the logo. Not PNG.

**Comment by sindresorhus** [comment]
I've moved the requests into separate issues:

- https://github.com/atomiclabs/cryptocurrency-icons/issues/165
- https://github.com/atomiclabs/cryptocurrency-icons/issues/166
- https://github.com/atomiclabs/cryptocurrency-icons/issues/163
- https://github.com/atomiclabs/cryptocurrency-icons/issues/167
- https://github.com/atomiclabs/cryptocurrency-icons/issues/168
- https://github.com/atomiclabs/cryptocurrency-icons/issues/169
- https://github.com/atomiclabs/cryptocurrency-icons/issues/170
- https://github.com/atomiclabs/cryptocurrency-icons/issues/171

Centrality was added in https://github.com/atomiclabs/cryptocurrency-icons/commit/4069b228f599851b4644f6adc0e1319a16e3ac47
