### ISSUE TITLE
Add SafeCoin (SAFE)

### ISSUE THREAD

**Issue by Fair-Exchange** [atomiclabs/cryptocurrency-icons#114]
Great project!  Please include SafeCoin :)
[SAFE]

https://bitcointalk.org/index.php?topic=2838370.0

http://safecoin.org
[logos updated.zip](https://github.com/cjdowner/cryptocurrency-icons/files/2037705/logos.updated.zip)

**Comment by petermumford** [comment]
Will this icon be added soon?

**Comment by lukechilds** [comment]
It will be added as soon as we can get around to it. Sorry for the delay.

**Comment by lukechilds** [comment]
That zip file is pretty big, can you just upload zip file of a vectorised version of your logo?
