### ISSUE TITLE
Add Gizer (GZR)

### ISSUE THREAD

**Issue by AbelCz** [atomiclabs/cryptocurrency-icons#116]
Hey,

I'm not an expert in photoshop so I'd like to request you guys to add the following logo for our "GZR" token:
![gizer_500x500](https://user-images.githubusercontent.com/17230732/40589719-d5fe5498-61f2-11e8-8139-6cd9c667a4aa.png)
![gizer_logo_256](https://user-images.githubusercontent.com/17230732/40589722-db7d4550-61f2-11e8-9513-7f3230711300.png)

**Comment by sindresorhus** [comment]
@AbelCz Thanks for the suggestion. Can you provide a [vector version](https://en.m.wikipedia.org/wiki/Vector_graphics) of the logo? SVG or source file, not PNG.

**Comment by sindresorhus** [comment]
I contacted the team and got the source: [gizer-logo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2298705/gizer-logo.zip)
