### ISSUE TITLE
Add Pigeoncoin (PGN)

### ISSUE THREAD

**Issue by gam777** [atomiclabs/cryptocurrency-icons#117]
Here is the github: https://github.com/Pigeoncoin/brand
Website: https://pigeoncoin.org

Thank You.

**Comment by sindresorhus** [comment]
@gam777 We will need a [vectorized version](https://en.m.wikipedia.org/wiki/Vector_graphics) of the logo (SVG or source file), not a bitmap like PNG. I don't see any SVG files in the linked repo. Can you ask someone from the team to provide it?

// @lukepighetti @minotaurdesign

**Comment by lukepighetti** [comment]
We'll get one linked ASAP.

Just want to throw you some praise, I've been using this repo for a couple side projects and it's fantastic.

**Comment by lukepighetti** [comment]
Deepest apologies. I completely forgot to follow up on this. I am going to reach out to our previous designer and try to get an SVG version for you.

**Comment by sindresorhus** [comment]
Closing for lack of vector logo.

**Comment by lukepighetti** [comment]
Yeah we lost our vector logo in team churn. a while back unfortunately. I'll ping you if I ever get around to reconstructing it.
