### ISSUE TITLE
Add ZestCoin (ZEST)

### ISSUE THREAD

**Issue by itamarcps** [atomiclabs/cryptocurrency-icons#118]
Hello,
I'm creating this commit with the objective to list Zest icon, on the following .zip you will find all the current icons and a .svg for it.

[Zest_Icons.zip](https://github.com/cjdowner/cryptocurrency-icons/files/2051166/Zest_Icons.zip)

Website: https://www.zestcoin.io/
Source Code: https://github.com/ZestFoundation/ZestCoin/

**Comment by sindresorhus** [comment]
The SVG you have provided is just a PNG embedded in an SVG file. We will need a proper [vectorized version](https://en.m.wikipedia.org/wiki/Vector_graphics) of the logo.

**Comment by sindresorhus** [comment]
I have properly vectorized the logo: [zest-logo.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2298428/zest-logo.svg.zip)
