### ISSUE TITLE
Add Commercium (CMM)

### ISSUE THREAD

**Issue by ilde1991** [atomiclabs/cryptocurrency-icons#121]
Hi. Can you please use the actual logo of Commercium (CMM). Here is the link. Thanks

https://www.commercium.net/cmm200.png

**Comment by sindresorhus** [comment]
@ilde1991 We will need a [vectorized version](https://en.m.wikipedia.org/wiki/Vector_graphics) of the logo (SVG or source file), not a bitmap like PNG.

**Comment by sindresorhus** [comment]
I found an SVG version of the logo here: https://commercium.net/img/logotype.svg

Attached here in case it disappears: [logotype.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2298312/logotype.svg.zip)
