### ISSUE TITLE
Add Storiqa (STQ)

### ISSUE THREAD

**Issue by memordial** [atomiclabs/cryptocurrency-icons#122]
Please add token Storiqa (STQ),
cmc: [https://coinmarketcap.com/currencies/storiqa/](https://coinmarketcap.com/currencies/storiqa/)
image: [https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-1/p320x320/20246018_1976532582614836_2357846549826288209_n.png?_nc_cat=0&_nc_eui2=AeEoYWqLU7WobHRvPQ3jOQmQSv6GjpUAwXJ7QQdsJ3fcEimQ4S5dFOx5dgLkT6HGr-UIRu1SS1zwSYtk0ryLr3HFE0vvW0hmXLsTcWY2MvhjMg&oh=fdaedbe24daf1ff4112f9005866ba4c2&oe=5B7D2FC3](https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-1/p320x320/20246018_1976532582614836_2357846549826288209_n.png?_nc_cat=0&_nc_eui2=AeEoYWqLU7WobHRvPQ3jOQmQSv6GjpUAwXJ7QQdsJ3fcEimQ4S5dFOx5dgLkT6HGr-UIRu1SS1zwSYtk0ryLr3HFE0vvW0hmXLsTcWY2MvhjMg&oh=fdaedbe24daf1ff4112f9005866ba4c2&oe=5B7D2FC3)

**Comment by memordial** [comment]
currently there is no vector format. this is the best image from their support. 

![img_0217](https://user-images.githubusercontent.com/226181/41018550-e7c5aaa4-698c-11e8-9757-327366e9f232.JPG)

**Comment by sindresorhus** [comment]
I have vectorized it: [stq.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2206608/stq.svg.zip)

**Comment by memordial** [comment]
@sindresorhus great, thanks

**Comment by memordial** [comment]
@sindresorhus great thanks, sorry i click wrong button
