### ISSUE TITLE
Add Ternio (TERN)

### ISSUE THREAD

**Issue by LegitLaz** [atomiclabs/cryptocurrency-icons#124]
[Ternio](https://Ternio.io) just got added today to the Delta app. Token is currently listed on SDEX (Stellarterm).

![white-yellow](https://user-images.githubusercontent.com/39858701/40877461-93f81b0e-6681-11e8-9097-ddcf7704da59.png)

Please use the abovestanding logo for Ternio, thanks in advance.

**Comment by sindresorhus** [comment]
@LegitLaz We will need a [vectorized version](https://en.m.wikipedia.org/wiki/Vector_graphics) of the logo (SVG or source file), not a bitmap like PNG.

**Comment by LegitLaz** [comment]
@sindresorhus you can get the file from here: https://ternio.io/images/ternio-logo.svg
