### ISSUE TITLE
Update PascalCoin (PASC)

### ISSUE THREAD

**Issue by Gus0918** [atomiclabs/cryptocurrency-icons#130]
Update the SVG logo file.
PASC pascalcoin has a new logo, here it is.

https://cdn.discordapp.com/attachments/398903932178661382/456736960539787265/Current_Logo_Clean_Hollow.svg

Thank you @sindresorhus

**Comment by sindresorhus** [comment]
@Gus0918 We will need a [vectorized version](https://en.m.wikipedia.org/wiki/Vector_graphics) of the logo (SVG or source file), not a bitmap like PNG.

**Comment by sindresorhus** [comment]
The issue body was updated with link to a SVG version.
