### ISSUE TITLE
Update Gimmer (GMR)

### ISSUE THREAD

**Issue by muzkle** [atomiclabs/cryptocurrency-icons#132]
Hi Delta team,

Please update our icon for Gimmer (GMR) on Delta App please.

You can find it attached, thanks!

[gimmer-icon-delta.zip](https://github.com/cjdowner/cryptocurrency-icons/files/2080494/gimmer-icon-delta.zip)

**Comment by muzkle** [comment]
Hi there,

Just checking, any issue with this update? Do we need to do something?
Just wondering if there's an ETA for this update?

Thanks!

**Comment by sindresorhus** [comment]
I managed to extract a vectorized version of their logo from their whitepaper: [gimmer-icon.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2298481/gimmer-icon.svg.zip)
