### ISSUE TITLE
Simplify the build script

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/cryptocurrency-icons#141]
It's currently a gigantic npm run script. Would be much simpler as just a Node.js script: `"build": "node build",`. No need for anything like webpack or gulp for this.

**Comment by imnotadeveloper** [comment]
In my opinion, there is no need for a build script.
The build script has been done because there was no website.
Since there is a website, it is not really necessary anymore.

About the website: the JS load the cryptos's names via api.coinmarketcap.com.
This is necessary because in the manifest.json there is only the symbol (not the name).
But as a result, the website is very slow.
If you are ok to add the cryptos's names in the manifest.json, I could delete the loading via api.coinmarketcap.com

The website will be much faster.

(I build the website, and I live in Chiang Mai too 😉)

**Comment by sindresorhus** [comment]
> In my opinion, there is no need for a build script.
The build script has been done because there was no website.
Since there is a website, it is not really necessary anymore.

Alright. Let's just remove it then. Want to do a pull request? :)

> If you are ok to add the cryptos's names in the manifest.json, I could delete the loading via api.coinmarketcap.com

👍 

I assume we can delete `Coin List.md` then too? Since that information would be in `manifest.json`.

> (I build the website, and I live in Chiang Mai too 😉)

Nice! I live in Bangkok though, but @lukechilds lives in Chiang Mai ;)

**Comment by lukechilds** [comment]
Btw, I think we should split out the website and the icons. This repo should just be the icons, we can have a separate repo for a static site that depends on this package via npm and loops over them. Or that could be a seperate project run by @imnotadeveloper if he would like to continue work on it.

Btw @imnotadeveloper message me on Twitter, we should meet sometime if you're free.

**Comment by imnotadeveloper** [comment]
> Alright. Let's just remove it then. Want to do a pull request? :)

I'd not prefer edit or remove the build script as I didn't build it.

> We can have a separate repo for a static site that depends on this package via npm and loops over them.

As soon as you separate the repos, I can publish a PR for the website and the `manifest.json` (to disconnect it from api.coinmarketcap.com)
But I don't want to host the project (Neither be credited 😉).

> Message me on Twitter

👍

**Comment by lukechilds** [comment]
@imnotadeveloper no problem, we are super busy trying to get HyperDEX shipped at the moment but I will try and set some time aside for this or get one of our developers on the job if I can't.

**Comment by sindresorhus** [comment]
> we can have a separate repo for a static site that depends on this package via npm and loops over them.

That would mean we need a build script and manually update the site whever we do a new release. How about instead we just make the website fetch the manifest file directly from this repo and the icons too. The manifest files gives the website the names and it can then just assume the paths.
