### ISSUE TITLE
Add BitCloud (BTDX)

### ISSUE THREAD

**Issue by c1xx** [atomiclabs/cryptocurrency-icons#143]
Hi Team,

please add our BitCloud icons / images. 
[Cryptocurrency-Icons.zip](https://github.com/hyperdexapp/cryptocurrency-icons/files/2135414/Cryptocurrency-Icons.zip)

If you need more Infos, please let me know.

Thank you,
Lukas

**Comment by c1xx** [comment]
How long does it take to add our logo(s) ?

**Comment by lukechilds** [comment]
Sorry for the delay, we will get round to it as soon as we're able to.

**Comment by c1xx** [comment]
Hey @lukechilds can you please tell me when you plan to do it?
