### ISSUE TITLE
Add GLX Token (GXLT)

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/cryptocurrency-icons#148]
Source: [GLXT.svg.zip](https://github.com/hyperdexapp/cryptocurrency-icons/files/2164979/GLXT.svg.zip)
Info: https://glx.co/glxt/
Brand guidelines: https://glx.co/media-kit/

**Comment by ronrusso** [comment]
Can you replace the old info for #148 with the info below:

Currency name: GLX Network Token
Symbol: GLXT
Website: http://glx.com
Theme color: #3b5998
Logo (SVG): https://drive.google.com/drive/folders/1iNAU3rzuFgqcsHm7QgQQk0L6BQSCoY1E?usp=sharing

**Comment by sindresorhus** [comment]
Done
