### ISSUE TITLE
Add Rupaya (RUPX)

### ISSUE THREAD

**Issue by zmulk** [atomiclabs/cryptocurrency-icons#149]
Hi could you add this logo to the delta app.

Ticker: RUPX
coin name: Rupaya

[Rupx.zip](https://github.com/hyperdexapp/cryptocurrency-icons/files/2173586/Rupx.zip)

website : www.rupx.io
thx

**Comment by sindresorhus** [comment]
@zmulk The SVG you've shared is just a PNG embedded in an SVG file. We need a real [vector](https://en.m.wikipedia.org/wiki/Vector_graphics) graphics, not bitmap.

**Comment by sindresorhus** [comment]
@mnzone-dev @rupaya-project Do you know where we can get a vector version of the logo?

**Comment by sindresorhus** [comment]
Closing for lack of vector logo.
