### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by VladimirHumeniuk** [atomiclabs/cryptocurrency-icons#153]
Hi, we need some more icons:

- Pundi (XNPXS)
- Mixin (XIN)
- Huobi Token (HT)
- MOAC (MOAC)
- Loom Network (LOOM)
- [Dropil (DROP)](https://dropil.com/branding/)
- Paypex (PAYX)

Could you please add them to your library?

**Comment by sindresorhus** [comment]
@VladimirHumeniuk We will need [vectorized versions](https://en.m.wikipedia.org/wiki/Vector_graphics) of the logos for those currencies. (SVG or source file, not a bitmap like PNG)

**Comment by VladimirHumeniuk** [comment]
@sindresorhus  i sent request for a vectorized logo to everyone of them via emails. I will give logos to you, if they give me an answers.

**Comment by sindresorhus** [comment]
@VladimirHumeniuk Can you open separate issues for each coin? That makes it easier for us to track. The issue title should be the coin name and symbol, example: `Paypex (PAYX)`

**Comment by sindresorhus** [comment]
@VladimirHumeniuk I saw you opened an issue for Dropil. I went ahead and opened issues for the rest of the coins for you.
