### ISSUE TITLE
Add TrueUSD (TUSD)

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/cryptocurrency-icons#161]
https://www.trusttoken.com/trueusd/
https://coinmarketcap.com/currencies/trueusd/

Media kit here, but no vector: https://drive.google.com/drive/folders/1W26zVFU5pEgWAuaVzm-abELnaxVYjUbl

**We need help finding a vector version of their logo.**

**Comment by syeo66** [comment]
Looks like a useful svg version. https://nomics.com/static/images/currencies/tusd.svg. 
However it is not an official source.
