### ISSUE TITLE
Add Dai (DAI)

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/cryptocurrency-icons#162]
http://www.makerdao.com/
https://coinmarketcap.com/currencies/dai/

**We need help finding a vector version of their logo.**

**Comment by giltotherescue** [comment]
Hey there. I reached out directly to the MakerDAO team and received several vector logo options in svg format:

https://cl.ly/7a97dcecdbb8
https://cl.ly/af1e31a3868d
https://cl.ly/5c689c348c2

Would it be possible to add the Dai logo soon? Thanks!

**Comment by ldub** [comment]
Probably not useful given the links above, but here is another SVG extracted from maker's own website: https://jsfiddle.net/0hzck4Ld/
