### ISSUE TITLE
Add HOLO (HOT)

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/cryptocurrency-icons#169]
https://holochain.org/
https://coinmarketcap.com/currencies/holo/

**We need help finding a vector version of their logo.**

**Comment by thedavidmeister** [comment]
@sindresorhus hmm, not something i've used before but i'm sure there is one around!

**Comment by thedavidmeister** [comment]
chasing up... will keep you posted

**Comment by sindresorhus** [comment]
Closing for lack of vector logo.

**Comment by thedavidmeister** [comment]
[holo-logo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2866837/holo-logo.zip)

here it is

**Comment by thedavidmeister** [comment]
@sindresorhus ^^
