### ISSUE TITLE
Add Huobi Token (HT)

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/cryptocurrency-icons#173]
https://www.huobi.com/en-us/
https://coinmarketcap.com/currencies/huobi-token/

**We need help finding a vector version of their logo.**

**Comment by VladimirHumeniuk** [comment]
Answer from Huobi Token about vectorized logo:

> Hi, we've checked with our management, i'm afraid we are not able to release the vector file to the public. You might want to consider obtaining non vector format from our social media twitter https://twitter.com/huobiglobal

**Comment by sindresorhus** [comment]
Their management clearly has no idea what vector format means.

Their website includes the vector logo, so here we go: [logo.aeb4723.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2212892/logo.aeb4723.svg.zip)
