### ISSUE TITLE
Add StarCoin (STR)

### ISSUE THREAD

**Issue by nextpulse** [atomiclabs/cryptocurrency-icons#187]
Currency name: StarCoin
Symbol: STR
Website: https://coinmarketcap.com/currencies/starcoin/

The coin is RIP. But for completeness.

**Comment by sindresorhus** [comment]
Please completely fill out the issue template. You are missing `Theme color` and `Logo (SVG)`.

**Comment by nextpulse** [comment]
The coin is dead - so difficult to locate logo etc
Are dead coins supported?

BTW: STR is used by Poloniex for XLM (!!). Really confusing.

**Comment by sindresorhus** [comment]
I don't think it's worth the effort to support dead coins. There are already way too many alive coins to support.
