### ISSUE TITLE
Add Bitcoin Hush (BTCH)

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/cryptocurrency-icons#197]
Currency name: Bitcoin Hush
Symbol: BTCH
Website: https://btchush.org
Theme color: #4700c2
Logo (SVG): https://github.com/bitcoinhush/bitcoinhush.github.io/files/2341213/SVG.Version.zip

Got the logo from https://github.com/bitcoinhush/bitcoinhush.github.io/issues/10.

**Comment by leto** [comment]
Let us know if anything else is needed
