### ISSUE TITLE
Add VET (VeChain)

### ISSUE THREAD

**Issue by levytskyy** [atomiclabs/cryptocurrency-icons#198]
Currency name:
Symbol:
Website:
Theme color:
Logo (SVG):

**Comment by sindresorhus** [comment]
Please fill out the issue template.

**Comment by syeo66** [comment]
@sindresorhus What do you think? How should name/symbol changes like this be handled.

**Comment by sindresorhus** [comment]
More info: https://www.reddit.com/r/Vechain/comments/8vnec8/what_is_vet_and_why_do_i_need_to_swap_ven_for_it/
