### ISSUE TITLE
Add CoinCollect (CC)

### ISSUE THREAD

**Issue by sindresorhus** [atomiclabs/cryptocurrency-icons#203]
Currency name: CoinCollect
Symbol: CC
Website: https://twitter.com/CoinCollectHQ
Theme color: #36b0f3
Logo (SVG): [cc-logo.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2372195/cc-logo.svg.zip)

I could only find a PNG of their logo, so I vectorized it.

**Comment by cipig** [comment]
[cc-logo_1.svg.gz](https://github.com/atomiclabs/cryptocurrency-icons/files/2379847/cc-logo_1.svg.gz)
I have attached a native SVG icon. Can you please use that?

**Comment by sindresorhus** [comment]
Yup
