### ISSUE TITLE
Add icon CoinCollect (CC)

### ISSUE THREAD

**Issue by brrrrrr** [atomiclabs/cryptocurrency-icons#212]
Currency name: CoinCollect
Symbol: CC
Website: https://coincollect.cc
Theme color: #ff9500
Logo (SVG): https://en.bitcoin.it/wiki/Promotional_graphics

[cc-logo_1.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2388000/cc-logo_1.svg.zip)

**Comment by sindresorhus** [comment]
Duplicate of #203
