### ISSUE TITLE
Change Cardano (ADA) background color

### ISSUE THREAD

**Issue by katomm** [atomiclabs/cryptocurrency-icons#215]
Thank you for this project, the Cardano (Ada) background feels wrong, please reconsider it. Should be *much* darker.

<img width="243" alt="example" src="https://user-images.githubusercontent.com/31965230/45665783-e3c5da00-bb12-11e8-9c11-a9345a50cceb.png">

**Comment by katomm** [comment]
You are right, the color is used for the font, but never as background for the logo. Please see the logos on:
https://cardanoroadmap.com/
https://daedaluswallet.io/
https://forum.cardano.org/
https://coinmarketcap.com/

**Comment by katomm** [comment]
Personally I think it should be #0d1e30 (matches also the offical sub on Reddit) or even a little brighter like #0f2230.

**Comment by lukechilds** [comment]
@katomm thanks, I'm not too up to date with Cardano, do you know any Cardano dev/designers GH handle that might be interested in giving us their opinion here?

**Comment by katomm** [comment]
No, I don't.

**Comment by lukechilds** [comment]
Ok, I think you're right though, looking through their branding `#0d1e30` seems to be more appropriate. Will flag this for updating.

**Comment by katomm** [comment]
Thank you @lukechilds. Is there a certain way how colors are selected? Because after digging into a few other logos it looks like many others are completely off-brand. 

Even the big ones like Ethereum and Bitcoin Cash. Please see:
https://www.ethereum.org/images/logos/Ethereum_Visual_Identity_1.0.0.pdf 
https://www.bitcoincash.org/graphics.html

**Comment by sunknudsen** [comment]
@sindresorhus, Cardano has changed it’s brand color to `#0033ad` (see https://cardano.org/ and https://www.coinbase.com/price/cardano).

> We don't accept pull request contributions for new or updated icons at this time. Open an issue and we'll do the icon for you.

Reporting this here so one of you can hopefully set background color to `#0033ad` (btw, SVG appears to be broken… file is messed up in Illustrator).

**Comment by lukechilds** [comment]
@spothq are the new maintainers of this repo, it's no longer me or @sindresorhus.
