### ISSUE TITLE
Missing 32@2x icons

### ISSUE THREAD

**Issue by lukechilds** [atomiclabs/cryptocurrency-icons#216]
I just noticed some of the more recent icons are missing in the `32@2x` folder. Ones I've noticed so far are EQLI and DNR.

We need to generate these from the Vectorised versions and make sure we have the Sketch file setup to automatically create these versions in the future.

**Comment by jenbuzz** [comment]
I ran a directory diff. The following are missing:

- bcbc
- dnr
- eqli
- mnz

**Comment by NadiaSotnikova** [comment]
I have a preset in Sketch always exporting the whole batch as 32@2x. Not sure how it happened, but I'll look into how the icons went missing, and will add them with my next batch of icons. 👌🏼🙂
