### ISSUE TITLE
Add BioCrypt (BIO)

### ISSUE THREAD

**Issue by BioCryptTechnologies** [atomiclabs/cryptocurrency-icons#217]
Currency name: BioCrypt
Symbol: BIO
Website: https://BioCrypt.Tech
Theme color: #00b0f0

ERC20 Smart Contract - 0xf18432ef894ef4b2a5726f933718f5a8cf9ff831

[Logo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2401684/Logo.zip)

**Comment by sindresorhus** [comment]
That is just a bitmap image embedded inside a SVG as a data URI. Open it in a text editor and you'll see. We need an actual vector image. https://en.wikipedia.org/wiki/Vector_graphics

**Comment by sindresorhus** [comment]
Closing for lack of response.
