### ISSUE TITLE
Add TrueGalaxyCash (TGCH)

### ISSUE THREAD

**Issue by galaxycash** [atomiclabs/cryptocurrency-icons#218]
Currency name: TrueGalaxyCash
Symbol: TGCH
Website: https://galaxycash.info
Theme color: #434247
[Logo.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2407643/Logo.svg.zip)

**Comment by sindresorhus** [comment]
We need an SVG version of the logo. You have only supplied a bitmap EPS and PNG.

**Comment by galaxycash** [comment]
Uploaded svg.

**Comment by sindresorhus** [comment]
There are still bitmap images embedded in the SVG. Open the source file and look for `data:image/png;base64`.

I've cleaned up the SVG file for you: [tgch-logo.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2407804/tgch-logo.svg.zip)
