### ISSUE TITLE
Add Ryo Currency (RYO)

### ISSUE THREAD

**Issue by IndeedMiners** [atomiclabs/cryptocurrency-icons#221]
Currency name: Ryo Currency
Symbol: RYO
Website: https://ryo-currency.com/
Theme color: #3299d3 and gradient #62c9f3 #3d58b0
Logo (SVG): [ryo-icon.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2407742/ryo-icon.zip)

**Comment by NadiaSotnikova** [comment]
I checked the logo file and looks like it's not a proper SVG, it's actually a bitmap image inside. We need an SVG so we can manipulate the colors and shapes.

**Comment by Mattthev** [comment]
Here it is [ryo-logo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2425256/ryo-logo.zip)

**Comment by IndeedMiners** [comment]
Is that logo the one you need?

**Comment by sindresorhus** [comment]
Yes, it is correct now.
