### ISSUE TITLE
Add Tezos (XTZ)

### ISSUE THREAD

**Issue by ReidDecentral** [atomiclabs/cryptocurrency-icons#222]
Add Tezos (XTZ)

Currency name: Tezos
Symbol: XTZ
Website: https://tezos.com/
Theme color: #2c7df7
Logo (SVG): http://icons.iconarchive.com/icons/cjdowner/cryptocurrency/256/Tezos-icon.png
Logo (SVG): [Tz.png.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2409156/Tz.png.zip)
Currency: https://en.wikipedia.org/wiki/Tezos

**Comment by sindresorhus** [comment]
The logo should be a SVG file (vector), not a PNG file (bitmap).

**Comment by syeo66** [comment]
Hm, do people even research before they request new icons?
XTZ already exists. @sindresorhus I think this can be closed.
