### ISSUE TITLE
Demo site doesn't work

### ISSUE THREAD

**Issue by dverbovyi** [atomiclabs/cryptocurrency-icons#223]
Hi there

Thank you all for the great work done here.

I've just found the cryptoicoins.co is empty and doesn't display any coins examples

<img width="1439" alt="screen shot 2018-09-24 at 15 09 11" src="https://user-images.githubusercontent.com/9499109/45951453-310ee380-c00c-11e8-8332-51eea4908369.png">

**Comment by jenbuzz** [comment]
See https://github.com/atomiclabs/cryptocurrency-icons-website/pull/5
