### ISSUE TITLE
Add QMCoin (QMC)

### ISSUE THREAD

**Issue by project-qmc** [atomiclabs/cryptocurrency-icons#227]
Currency name: QMCoin
Symbol: QMC
Website: https://bitcointalk.org/index.php?topic=5036896.0
Theme color: #feb043
Logo (SVG): https://transfer.sh/FngNH/overview.svg

**Comment by sindresorhus** [comment]
The SVG you have included is just a bitmap image embedded in a SVG. We need an actual vectorized image. Note the `data:image/png;base64,` part in the SVG source.

https://en.wikipedia.org/wiki/Vector_graphics

**Comment by project-qmc** [comment]
Did not notice that, sorry - was relying on imagemagic...will fix and resubmit

**Comment by project-qmc** [comment]
Here you go - https://transfer.sh/14SZV/overview.svg

**Comment by sindresorhus** [comment]
Still not correct. I'm not sure what you did, but it kinda seems like you converted each pixel in the image to a vector square. The image is almost 700 KB. It should be no more than 30 KB.

**Comment by sindresorhus** [comment]
Closing for lack of vector logo.
