### ISSUE TITLE
Add GLX Network Token (GLXT)

### ISSUE THREAD

**Issue by ronrusso** [atomiclabs/cryptocurrency-icons#228]
Currency name: GLX Network Token
Symbol: GLXT
Website: http://glx.com
Theme color: #3b5998
Logo (SVG): https://drive.google.com/drive/folders/1iNAU3rzuFgqcsHm7QgQQk0L6BQSCoY1E?usp=sharing

**Comment by sindresorhus** [comment]
The SVG you've shared is just a bitmap image embedded in a SVG file. Note the `data:image/jpeg;base64` in the source. The SVG needs to be a proper [**vector** image](https://en.wikipedia.org/wiki/Vector_graphics).

**Comment by sindresorhus** [comment]
We actually already have this one, but there was a typo in the name.

**Comment by ronrusso** [comment]
I will create a proper svg file.  Can you please open this back up.  These are two separate tokens.  X is an STO22 token that represents the equity in GLX and GLXT is our utility token built on the Komodo blockchain.  Although they appear similar you can see every single field is different.

Currency name: GLX Network Token
Symbol: GLXT
Website: http://glx.com
Theme color: #3b5998
Logo (SVG): https://drive.google.com/drive/folders/1iNAU3rzuFgqcsHm7QgQQk0L6BQSCoY1E?usp=sharing

Currency name: GLX Equity Token
Symbol: X
Website: http://glx.com
Theme color: #282A3C
Logo (SVG): https://drive.google.com/drive/folders/14ml3-smK1inEo5mlRr1HkPltupFpCHJS?usp=sharing
