### ISSUE TITLE
Add GLX Equity Token (X)

### ISSUE THREAD

**Issue by ronrusso** [atomiclabs/cryptocurrency-icons#229]
Currency name: GLX Equity Token
Symbol: X
Website: http://glx.com
Theme color: #3b5998
Logo (SVG): https://drive.google.com/drive/folders/14ml3-smK1inEo5mlRr1HkPltupFpCHJS?usp=sharing

**Comment by sindresorhus** [comment]
Same as https://github.com/atomiclabs/cryptocurrency-icons/issues/228#issuecomment-427653668

**Comment by ronrusso** [comment]
The new svg has been updated in the folder - https://drive.google.com/drive/folders/14ml3-smK1inEo5mlRr1HkPltupFpCHJS?.

Please let me know if you have any problems.

**Comment by sindresorhus** [comment]
It is still just a bitmap image embedded in the SVG image.

**Comment by ronrusso** [comment]
OK I changed the resolution to the embedded image.  I just uploaded the new svg. Please tell me if it is OK now.

**Comment by sindresorhus** [comment]
> OK I changed the resolution to the embedded image. 

That doesn't help.

> Please tell me if it is OK now.

Still the same issue as commented above.

**Comment by sindresorhus** [comment]
Please read up on what a vector image means: https://en.wikipedia.org/wiki/Vector_graphics

**Comment by sindresorhus** [comment]
What app was the X icon made with? What file format is the source file? Can you share the source file?

**Comment by ronrusso** [comment]
Sure. Both are Adobe.  One is a psd and that psd is embedded into the Illustrator file.  I will put the both of them in the public folder.  I was even on the phone with Adobe support.  I do not know what I could have done wrong.

**Comment by ronrusso** [comment]
OK bot the psd and the ai files are in there now

**Comment by ronrusso** [comment]
Thank you so much. I will review the files.
