### ISSUE TITLE
Add TokenPay (TPAY)

### ISSUE THREAD

**Issue by sakib25** [atomiclabs/cryptocurrency-icons#231]
Currency name: TokenPay
Symbol: TPAY
Website: https://www.tokenpay.com/
Theme color: #3058a6
Logo (SVG): 
[TokenPay logo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2471677/TokenPay.logo.zip)

**Comment by sindresorhus** [comment]
You did not read the issue template:

> Ensure the SVG file is a proper vector file and not just embedding a PNG/JPEG file. If the SVG source contains `data:image/png;base64`/`data:image/jpeg;base64` or its size is larger than 100 KB, it's not a valid vectorized SVG file.

The embedded SVG is not valid. See https://github.com/atomiclabs/cryptocurrency-icons/issues/229 for context.

**Comment by sakib25** [comment]
Hi
See if this SVG file is ok
[tpay svg logo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2473079/tpay.svg.logo.zip)

**Comment by sindresorhus** [comment]
Yes, good now.
