### ISSUE TITLE
Add Turkish lira (TRY)

### ISSUE THREAD

**Issue by VSG24** [atomiclabs/cryptocurrency-icons#234]
Currency name: Turkish lira
Symbol: TRY
Website: http://www.tcmb.gov.tr/wps/wcm/connect/en/tcmb+en
Theme color: #00648a
Logo (SVG): https://en.wikipedia.org/wiki/Turkish_lira#/media/File:Turkish_lira_symbol_black.svg

**Comment by sindresorhus** [comment]
Hey, we have decided not to add additional fiat currencies as it's outside the scope of this project. We will not remove the few we have, but we're not interested in adding more.
