### ISSUE TITLE
Update Currency Horizen (ZEN)

### ISSUE THREAD

**Issue by bagintz** [atomiclabs/cryptocurrency-icons#237]
I believe that the new branding includes new image assets for the coin

horizen.global

**Comment by sindresorhus** [comment]
Please fill out the issue template.

**Comment by bagintz** [comment]
Currency name: Horizen
Symbol: ZEN
Website: https://horizen.global
Theme color: #16203A (??)
Logo (SVG): [horizen.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2574523/horizen.svg.zip)

**Comment by bagintz** [comment]
Does that ^^ work?
