### ISSUE TITLE
Add Aywa (AYWA)

### ISSUE THREAD

**Issue by GetAywa** [atomiclabs/cryptocurrency-icons#240]
Currency name: Aywa
Symbol: AYWA
Website: http://getaywa.org
Theme color: #3355B5
Logo (SVG): [Aywa_logo-2.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2602647/Aywa_logo-2.svg.zip)

**Comment by sindresorhus** [comment]
This is not valid vector image. It seems you have just automatically tried to vectorize a 3D logo.

From the issue template:

> Ensure the SVG file is a proper vector file and not just embedding a PNG/JPEG file. If the SVG source contains `data:image/png;base64`/`data:image/jpeg;base64` or its size is larger than 100 KB, it's not a valid vectorized SVG file.

**Comment by GetAywa** [comment]
file updated

**Comment by GetAywa** [comment]
hi, updated file attached!

**Comment by sindresorhus** [comment]
Alright, it's good now.
