### ISSUE TITLE
Add Aywa (AYWA)

### ISSUE THREAD

**Issue by GetAywa** [atomiclabs/cryptocurrency-icons#242]
Currency name:Aywa
Symbol:AYWA
Website:http://getaywa.org
Theme color:#3355B5
Logo (SVG):[Aywa_logo.svg 2.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2600348/Aywa_logo.svg.2.zip)

**Comment by sindresorhus** [comment]
No need to open a new issue. Please continue the discussion in #240.
