### ISSUE TITLE
Add EOS Network (EON)

### ISSUE THREAD

**Issue by mairav** [atomiclabs/cryptocurrency-icons#250]
Currency name: EOS Network
Symbol: EON
Website: https://eon.org/
Theme color: #443f54
Logo (SVG): https://upload.wikimedia.org/wikipedia/commons/8/8d/Eosio_logo.svg

**Comment by mairav** [comment]
Do you still need this logo?

**Comment by sindresorhus** [comment]
Yes. ZIP it and attach it directly to your GitHub comment this time.

**Comment by NadiaSotnikova** [comment]
@mairav When I go to this link, it says the file isn't found. https://upload.wikimedia.org/wikipedia/commons/8/8d/Eosio_logo.svg

**Comment by mairav** [comment]
The logo was there when I created the issue. Give me some days and I'll do it myself along with some more coins that are missing. I'm kind of busy right now.

**Comment by mairav** [comment]
[eon.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2895955/eon.zip)
There you have.

**Comment by sindresorhus** [comment]
@mairav That one is not accurate. The official icon has some of the lines with lower opacity. Try to find the official logo instead of making your own.

**Comment by mairav** [comment]
[eon.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2897236/eon.zip)
couldn't find one in svg format, that's why i dit it myself. 

I made it plain cause i don't know the rules to take into account when vectorizing them. I send you an email yesterday about this. Can you give me a guide please of what you accept and not in the logos?

**Comment by sindresorhus** [comment]
This one looks better.

**Comment by mairav** [comment]
Do you have an ETA for all this icons to be included? is there something else I can do to help you launch them?
