### ISSUE TITLE
Add Atidium (ATD)

### ISSUE THREAD

**Issue by mairav** [atomiclabs/cryptocurrency-icons#253]
Currency name: Atidium
Symbol: ATD
Website: https://www.atidium.io/
Theme color: #2f4999
Logo (SVG): couldn't find a vector logo. This is what I found.
[atd.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2631782/atd.zip)

**Comment by sindresorhus** [comment]
We need a valid SVG logo to be able to create an icon. You could try contacting the ATD owners about it.

**Comment by mairav** [comment]
[atd (2).zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2649819/atd.2.zip)
This is what the people of Atiudium gave me. It's like they took the original logo and convert it to vector file with some automatic tool. Tell me if it can be used.

**Comment by sindresorhus** [comment]
It cannot be used.

**Comment by sindresorhus** [comment]
Closing for lack of vector logo.

**Comment by mairav** [comment]
Background color: #e94b25
Logo color: #0d3755
[atd.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2896369/atd.zip)
