### ISSUE TITLE
Add icon for missing currencies

### ISSUE THREAD

**Issue by mairav** [atomiclabs/cryptocurrency-icons#255]
Is it possible to create a special icon for currencies that do not have their own icon yet? Like a question mark, and that it can be reached with a class like "missing".

In this way, if I look for an image in my app, and its missing, i add the "missing" class, to show something instead of a broken image link.

**Comment by sindresorhus** [comment]
We have that actually: https://github.com/atomiclabs/cryptocurrency-icons/blob/master/svg/color/generic.svg We just forgot to document it.

**Comment by mairav** [comment]
Great, thanks for your fast reply!
