### ISSUE TITLE
Add GINcoin (GIN)

### ISSUE THREAD

**Issue by SideKickAppAI** [atomiclabs/cryptocurrency-icons#256]
Currency name: GINcoin
Symbol: GIN
Website: https://gincoin.io
Theme color: #008DDE
Logo (PNG): https://s2.coinmarketcap.com/static/img/coins/32x32/2773.png

**Comment by sindresorhus** [comment]
Please read and adhere to the [issue template](https://raw.githubusercontent.com/atomiclabs/cryptocurrency-icons/master/.github/ISSUE_TEMPLATE.md). We need a vector SVG logo, not PNG.

**Comment by SideKickAppAI** [comment]
[gin-white.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2649697/gin-white.zip)
Here is the white svg, but if you look at theme color above, that's the color they normally use (just couldn't get the color svg now).. so if you don't mind, could you make a version with the #008DDE? 

Thanks!
