### ISSUE TITLE
Add Presearch (PRE)

### ISSUE THREAD

**Issue by SideKickAppAI** [atomiclabs/cryptocurrency-icons#258]
Currency name: Presearch
Symbol: PRE
Website: https://presearch.org
Theme color: #3A8CBD
Logo (PNG): view-source:https://presearch.org/favicon.png

**Comment by sindresorhus** [comment]
Please read and adhere to the [issue template](https://raw.githubusercontent.com/atomiclabs/cryptocurrency-icons/master/.github/ISSUE_TEMPLATE.md). We need a vector SVG logo, not PNG.

**Comment by SideKickAppAI** [comment]
Sorry, here you go! Thanks!

[Presearch.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2649365/Presearch.zip)
