### ISSUE TITLE
ADD IOTA ALTCOIN

### ISSUE THREAD

**Issue by ruden91** [atomiclabs/cryptocurrency-icons#268]
Currency name: iota
Symbol: iota
Website: https://www.iota.org/
Theme color: #000
Logo (SVG): https://commons.wikimedia.org/wiki/File:Iota_logo.svg

**Comment by sindresorhus** [comment]
Please follow the issue template exactly. That means the exact issue title and casing.

**Comment by syeo66** [comment]
Hm, IOTA is actually there... It's just called miota (coinmarketcap is also using miota as Symbol)
