### ISSUE TITLE
Update Bitcoin Cash (BCH) Icon Color from Green to Orange

### ISSUE THREAD

**Issue by BUYMERCIER** [atomiclabs/cryptocurrency-icons#271]
Currency name: Bitcoin Cash
Symbol: BCH
Website: https://bitcoincash.org
Theme color: #F59332
Logo (SVG): https://www.bitcoincash.org/graphics.html

Most exchanges, wallets and services use the Orange color for the Bitcoin Cash logo.
(It is true that a couple of exchanges use Green colors, just as some exchanges use the ticker `XBT` for Bitcoin (BTC))

Here attached are the corrected Bitcoin Cash logos in the requested formats:
[BCH-cryptocurrency-icons-master.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2753386/BCH-cryptocurrency-icons-master.zip)

**Comment by sindresorhus** [comment]
See https://github.com/atomiclabs/cryptocurrency-icons/issues/26

**Comment by BUYMERCIER** [comment]
#26 is misleading and should be reverted.
See by yourself on bitcoincash.org, the Orange color is used as well as on most platforms

**Comment by sindresorhus** [comment]
// @seth-reeser

**Comment by seth-reeser** [comment]
The slant of the ₿ is less memorable than orange vs green. Although the BitcoinCash official logo color is orange, parts of the community feel that this is driven by the desire for market share rather than creating it's own identity.

**Comment by maplesyrupsucker** [comment]
> The slant of the ₿ is less memorable than orange vs green. Although the BitcoinCash official logo color is orange, parts of the community feel that this is driven by the desire for market share rather than creating it's own identity.

Which community? BTC community? LTC community? NEM community? Since when do we allow one coins community to determine what another coin should be represented as?

**Comment by BUYMERCIER** [comment]
> help users from mistaking Bitcoin Cash from Bitcoin when sending and receiving.
- Quote from #26 

@seth-reeser I understand your concern about confusing both currencies and potential loss of funds for new users.
Though, it is not possible to send BTC to a BCH address by mistake anymore (and since quite a while) as the address format for Bitcoin Cash is now different 😃.

Here is an example of a Bitcoin Cash address: `bitcoincash:qp0gechl0zf6qe66tug0fuq249jj764dkc9rgczzwr`. 

Indeed, entering this address in a BTC wallet would display an error. In the same way, entering a BTC address in a BCH wallet would result in a warning or an error.


Please consider restoring the original and most widely used color of the BCH logo and do not fall in the trolls' game. Thank you 🙏🏻

**Comment by razorsyntax** [comment]
Our application uses the green icon for the practical reason of not confusing our customers.  If the BCH icon ever changes enough that it no longer confuses BTC at a glance, we will happily update it. 
 This isn't specific to BCH.  We do the same for other icons which look too similar at a glance as well.

**Comment by BUYMERCIER** [comment]
Your application definitely does confuse your users as it even lists a currency that does not exist: Bitcoin ABC.

It also lists the known Ponzi scheme Bitconnect while your team is concerned with new users sending funds to the wrong address by mistake..

Good luck with your project.

**Comment by razorsyntax** [comment]
Please avoid resorting to belittling our application when you don't know what our application is.  No, we don't list Bitcoin Cash as Bitcoin ABC.  No, we don't list Bitconnect (this discussion has nothing to do with Bitconnect.  Why even bring it up?).

Moreover, no need for the hostility here.  No one is attacking you personally or BCH for that matter.

Green will remain BCH's color in our application and all marketing materials until its logo can no longer be confused with BTC.

**Comment by BUYMERCIER** [comment]
![60e9a26a-27ec-49e4-aeb3-cacbfdf3bfae](https://user-images.githubusercontent.com/21960643/51351356-46d57680-1add-11e9-92bb-6d93230c8916.png)

**Comment by razorsyntax** [comment]
Not my application.  We're a user of some of this repository's icons.  And no... Bitcoin ABC is not used in our application.
