### ISSUE TITLE
Add Blockchain.io (BCIO)

### ISSUE THREAD

**Issue by Victorlabrusse** [atomiclabs/cryptocurrency-icons#274]
Currency name: Blockchain.io
Symbol: BCIO
Website: https://blockchain.io/
Theme color: 3F43AD
Logo (SVG): https://blockchain.io/wp-content/uploads/2019/02/bcio.svg

**Comment by sindresorhus** [comment]
Doesn't look like the name is BCIO.

**Comment by Victorlabrusse** [comment]
I just get the confirmation that you can use "Blockchain.io" as name. Thank you.
