### ISSUE TITLE
Add MEET.ONE (MEETONE)

### ISSUE THREAD

**Issue by mairav** [atomiclabs/cryptocurrency-icons#277]
Currency name: MEET.ONE
Symbol: MEETONE
Website: https://meet.one/
Theme color: Background: #000, Logo: #FFF
Logo (SVG):
[meetone.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2896175/meetone.zip)

**Comment by sindresorhus** [comment]
That SVG contains an embedded bitmap image. Fixed here: [meetone.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2896827/meetone.svg.zip)
