### ISSUE TITLE
Add EOP (EOP)

### ISSUE THREAD

**Issue by mairav** [atomiclabs/cryptocurrency-icons#279]
Currency name: EOP
Symbol: EOP
Website: I dont know
Theme color: #35a7df
Logo (SVG): [eop.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2896199/eop.zip)

**Comment by sindresorhus** [comment]
We need a website. And I doubt `EOP` is the name.

**Comment by mairav** [comment]
You can see here, that its symbol is EOP and it's name is also EOP: https://info.binance.com/en/currencies/eop
Binance says the  website is: eospace.io

For BTC the make the difference in the title as BTC Bitcoin
https://info.binance.com/en/currencies/bitcoin

**Comment by sindresorhus** [comment]
Alright
