### ISSUE TITLE
Add Augmint Euro Token (AEUR)

### ISSUE THREAD

**Issue by keo** [atomiclabs/cryptocurrency-icons#280]
Currency name: Augmint Euro Token
Symbol: AEUR
Website: https://www.augmint.org
Theme color: #051d2d
Logo (SVG): https://drive.google.com/drive/folders/14oZ8ZPgYcnUiskHeisIhaPcvM-vEu6Ul

**Comment by sindresorhus** [comment]
You have written the currency name different in the title and the description.

**Comment by sindresorhus** [comment]
The SVG logo also doesn't show anything for me.

**Comment by keo** [comment]
fixed it

where could I get the Sketch template from? (mentioned in https://github.com/atomiclabs/cryptocurrency-icons/wiki)

**Comment by sindresorhus** [comment]
> where could I get the Sketch template from? (mentioned in [atomiclabs/cryptocurrency-icons/wiki](https://github.com/atomiclabs/cryptocurrency-icons/wiki))

[Cryptocurrency Icons.sketch.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2918558/Cryptocurrency.Icons.sketch.zip)

Note that we don't accept direct icon contributions.

**Comment by keo** [comment]
thank you - it will help us in the interim anyway, until you do it yourself.
