### ISSUE TITLE
Theme color in manifest.json for each icon

### ISSUE THREAD

**Issue by m-tymchyk** [atomiclabs/cryptocurrency-icons#285]
Will you add theme and foreground color for each icon?

**Comment by sindresorhus** [comment]
The foreground color is always white, but I can see the theme color being useful. PR welcome to add that.

**Comment by sindresorhus** [comment]
This was added in https://github.com/atomiclabs/cryptocurrency-icons/commit/7be9023fbaea24367cab2b9a5a5f316077bb2309.
