### ISSUE TITLE
Update Stellar Lumens (XLM)

### ISSUE THREAD

**Issue by mikeyrf** [atomiclabs/cryptocurrency-icons#287]
Update XLM to match Stellar's new redesign:
Announcement: https://medium.com/stellar-development-foundation/announcing-the-new-stellar-logo-81eb4fafe1b0
Vector graphics: https://www.stellar.org/roadmap/stellar_new_brand.zip

Currency name: Stellar Lumens
Symbol: XLM
Website: https://www.stellar.org/roadmap/
Theme colors: #000000, #e1e1e1, #ffa51e, #ff5500, #7d00ff, #00aa46
Logo (SVG): https://www.stellar.org/roadmap/stellar_new_brand.zip

**Comment by sindresorhus** [comment]
Please provide only one theme color, the main one, which will be used for the icon.

The provided logo looks good, but the ZIP is quite large, so I'm attaching just the SVG for convenience: [Stellar_symbol_black_RGB.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2955164/Stellar_symbol_black_RGB.svg.zip)

**Comment by mikeyrf** [comment]
Sounds good. Thanks

Theme color: #000000

**Comment by apswak** [comment]
Hi @sindresorhus - know you're very busy but was wondering if there's anything I can do to get this one and/or others in? Is there a reason you don't accept help via PR's anymore?
