### ISSUE TITLE
Add Crypto.com Chain (CRO)

### ISSUE THREAD

**Issue by syeo66** [atomiclabs/cryptocurrency-icons#292]
Currency name: Crypto.com Chain
Symbol: CRO
Website: https://crypto.com/en/chain.html
Theme color: #222d58 (or #233868 or #202046 - depending on the part of the gradient)
Logo (SVG): Unfortunately could not find one - wanted to ask them right now but couldn't reach the website because of some major network outage

Will try again later

**Comment by syeo66** [comment]
Asked for a SVG logo

**Comment by syeo66** [comment]
unfortunately they seem not to be interested...

"Thank you for reaching us out.

Unfortunately we are unable to provide you with such an icon for that purpose."

**Comment by CPatchane** [comment]
What about using this one @syeo66 https://github.com/crypto-com/chain/blob/master/assets/logo.svg?
I guess we can crop to get only the circle icon
