### ISSUE TITLE
Add BlitzPredict (XBP)

### ISSUE THREAD

**Issue by brettrichey** [atomiclabs/cryptocurrency-icons#296]
Currency name: BlitzPredict
Symbol: XBP
Website: https://blitzpredict.io
Theme color: `#21AF67`
Logo (SVG): [bp-logo-svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3075489/bp-logo-svg.zip)

**Comment by co16353sidak** [comment]
I would love to work on this as my first issue here, If I could possibly get the go ahead ? @sindresorhus

**Comment by sindresorhus** [comment]
@co16353sidak Sorry, we don't accept icon contributions as we want to ensure a high standard and consistency.
