### ISSUE TITLE
Add GoldCoin (GLC)

### ISSUE THREAD

**Issue by pulsoftgit** [atomiclabs/cryptocurrency-icons#297]
Currency name: GoldCoin
Symbol: GLC
Website: https://www.goldcoin.org/
Theme color: #DDBC64
Logo (SVG): http://www.goldcoin.org/img/logoCOIN.svg

**Comment by sindresorhus** [comment]
Please read the issue template:

> Ensure the SVG file is a proper vector file and not just embedding a PNG/JPEG file. **If the SVG source contains `data:image/png;base64`/`data:image/jpeg;base64`** or its size is larger than 100 KB, it's not a valid vectorized SVG file.
