### ISSUE TITLE
Add COSMOS (ATOM)

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [atomiclabs/cryptocurrency-icons#299]
Currency name: COSMOS
Symbol: ATOM
Website: https://cosmos.network
Theme color: `#2e3148`
Logo (SVG): [atom-logo-svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3140861/atom-logo-svg.zip)

**Comment by sindresorhus** [comment]
Please follow the issue template instructions.

**Comment by DESIGNfromWITHIN** [comment]
Updated

**Comment by sindresorhus** [comment]
The attached SVG is not valid. It's just an SVG that links to a bitmap image.

**Comment by DESIGNfromWITHIN** [comment]
Updated, think its good now.

**Comment by sindresorhus** [comment]
Yup
