### ISSUE TITLE
Add Celer Network (CELR)

### ISSUE THREAD

**Issue by Paulsky** [atomiclabs/cryptocurrency-icons#303]
Currency name: Celer Network
Symbol: CELR
Website: https://www.celer.network
Theme color: #212529
Logo (SVG): https://drive.google.com/file/d/16_OeoSdU558x37lNQRTfZXWJP0bXPpqy/view

**Comment by sindresorhus** [comment]
We need a symbol to make the icon, not a text logo.

**Comment by Paulsky** [comment]
My apologies! I will search for a symbol!

**Comment by sindresorhus** [comment]
Just text will not really work on our icons.

**Comment by Paulsky** [comment]
Okay, I understand. I will close this issue for now. Thank you and my apologies.
