### ISSUE TITLE
Add Ren (REN)

### ISSUE THREAD

**Issue by Paulsky** [atomiclabs/cryptocurrency-icons#305]
Currency name: Ren
Symbol: REN
Website: https://renproject.io/
Theme color: #001b3a
Logo (SVG): [ren.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3216415/ren.zip) (from: https://renproject.io/static/media/logo.5f775a47.svg)

**Comment by sindresorhus** [comment]
Per the issue template, embed the SVG in the issue (We ask this so it doesn't suddenly go away.)

**Comment by Paulsky** [comment]
Understood. I added a .zip file which contains the SVG file.
