### ISSUE TITLE
Add MisoCoin (MIS)

### ISSUE THREAD

**Issue by hibuddha** [atomiclabs/cryptocurrency-icons#308]
Currency name: MisoCoin
Symbol: MIS
Website: dlive.tv/travio33
Theme color: #dbf1fe
Logo (SVG): [Saved Pictures.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3245085/Saved.Pictures.zip)

**Comment by sindresorhus** [comment]
Closing as the website just links to a live stream and the icon is just a dog picture.
