### ISSUE TITLE
Add 0xBitcoin (0xBTC)

### ISSUE THREAD

**Issue by 0xBrian** [atomiclabs/cryptocurrency-icons#309]
Currency name: 0xBitcoin
Symbol: 0xBTC
Website: https://0xbitcoin.org/
Theme color: #ff914d
Logo (SVG): https://github.com/0xBrian/0xBitcoin-media/blob/master/logos/0xbitcoin-logo-flat2.svg

[0xbitcoin-logo-flat2.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3255454/0xbitcoin-logo-flat2.svg.zip)

**Comment by sindresorhus** [comment]
Please ZIP and attach the SVG to the issue, per the issue template instructions.

**Comment by 0xBrian** [comment]
Sorry, it looks to me like the instructions say "Either embed the logo as a ZIP file or link to somewhere we can download it." But I've zipped it and attached it. Thanks.

**Comment by 0xBrian** [comment]
Oh, I see now that you mean to zip it regardless of whether the submitter chooses to attach it or provide a link to it. I respectfully think the wording is unclear. Thanks.
