### ISSUE TITLE
Add LEO (UNUS SED LEO)

### ISSUE THREAD

**Issue by abrkn** [atomiclabs/cryptocurrency-icons#312]
Currency name: UNUS SED LEO
Symbol: LEO
Website: https://www.bitfinex.com/wp-2019-05.pdf
Theme color: TBD
Logo (SVG): TBD

**Comment by sindresorhus** [comment]
No point in opening an issue until you actually have the logo and color. That creates needless noise.

**Comment by abrkn** [comment]
Sorry, @sindresorhus. I am adding a $25 bounty to this issue through BountySource. Is that okay or should I work from a fork?

**Comment by sindresorhus** [comment]
This is not the place to get someone to create a logo for a project. We work off existing logos. So yes, working off a fork until there's an actual logo would be better.

**Comment by Paulsky** [comment]
@abrkn Please check this issue: #326
