### ISSUE TITLE
Add Bitcoin Cash Liquid (L-BCH)

### ISSUE THREAD

**Issue by adventuresofblake** [atomiclabs/cryptocurrency-icons#320]
Currency name: Bitcoin Cash Liquid
Symbol: L-BCH
Website: https://blockstream.com/liquid/
Theme color: `#8dc351`
Logo (SVG): 
[Bitcoin Cash Liquid.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3320404/Bitcoin.Cash.Liquid.zip)

**Comment by sindresorhus** [comment]
We don't accept "meta coins", see https://github.com/atomiclabs/cryptocurrency-icons/issues/304
