### ISSUE TITLE
Add Bitcoin Liquid (L-BTC)

### ISSUE THREAD

**Issue by adventuresofblake** [atomiclabs/cryptocurrency-icons#321]
Currency name: Bitcoin Liquid
Symbol: L-BTC
Website: https://blockstream.com/liquid/
Theme color: #f7931a
Logo (SVG):
[Bitcoin Liquid.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3320407/Bitcoin.Liquid.zip)

**Comment by sindresorhus** [comment]
https://github.com/atomiclabs/cryptocurrency-icons/issues/320#issuecomment-507789607
