### ISSUE TITLE
Add Bitcoin Lightning (LN)

### ISSUE THREAD

**Issue by adventuresofblake** [atomiclabs/cryptocurrency-icons#322]
Currency name: Bitcoin Lightning
Symbol: LN
Website: https://lightning.network/
Theme color:
Logo (SVG): #f7931a
[Bitcoin LN.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3320429/Bitcoin.LN.zip)

**Comment by sindresorhus** [comment]
This is a Bitcoin tech, not a separate coin.
