### ISSUE TITLE
Add Zcash Shielded

### ISSUE THREAD

**Issue by adventuresofblake** [atomiclabs/cryptocurrency-icons#324]
Currency name: Zcash Shielded
Symbol: ZEC
Website: https://z.cash
Theme color: #ecb244
Logo (SVG):  
[ZCash Shield.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3320475/ZCash.Shield.zip)

**Comment by sindresorhus** [comment]
This is not a coin.
