### ISSUE TITLE
Add ZCash Transparent

### ISSUE THREAD

**Issue by adventuresofblake** [atomiclabs/cryptocurrency-icons#325]
Currency name: ZCash Transparent
Symbol: ZEC
Website: https://z.cash
Theme color: #ecb244
Logo (SVG): 
[ZCash Transparent.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3320476/ZCash.Transparent.zip)

**Comment by sindresorhus** [comment]
This is not a coin.
