### ISSUE TITLE
Add Veles (VLS)

### ISSUE THREAD

**Issue by Paulsky** [atomiclabs/cryptocurrency-icons#336]
Currency name: Veles
Symbol: VLS
Website: https://veles.network/
Theme color: `#e4b99c`
Logo (SVG): [veles-logo.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/3488976/veles-logo.zip)

**Comment by sindresorhus** [comment]
The logo is not valid. It's just a vectorized bitmap and the file is 1.5 MB.

**Comment by Paulsky** [comment]
Sorry about that! I will try to find a correct SVG.

**Comment by Paulsky** [comment]
I'm closing this for now, because I can't get a correct SVG.
