### ISSUE TITLE
Update Verge (XVG) Logo

### ISSUE THREAD

**Issue by Max1us** [atomiclabs/cryptocurrency-icons#342]
Currency name: Verge
Symbol: XVG
Website: https://vergecurrency.com
Logos: https://github.com/vergecurrency/verge-graphics/tree/master/Primary%20Logo

Thank you kindly

**Comment by sindresorhus** [comment]
Please follow the issue template instructions.

**Comment by Max1us** [comment]
It's an update of the existing. The vector assets are already in the github url.

**Comment by sindresorhus** [comment]
The issue template still applies.
