### ISSUE TITLE
Add Algorand (ALGO)

### ISSUE THREAD

**Issue by C0DK** [atomiclabs/cryptocurrency-icons#364]
Currency name: Algorand
Symbol: ALGO
Website: https://www.algorand.com/
Theme color: ??
Logo (SVG): https://cryptologos.cc/logos/algorand-algo-logo.svg?v=001

**Comment by bchoubert** [comment]
Already requested on #341

**Comment by C0DK** [comment]
true. i'll close this, and hope yours get merged soon
