### ISSUE TITLE
cryptocurrency-icons abandoned?

### ISSUE THREAD

**Issue by syeo66** [atomiclabs/cryptocurrency-icons#365]
Hey
I see the last commit was in August 2019. Are those icons abandoned? Can we still expect updates?

Maybe you should reconsider accepting PRs and add some additional maintainers.
Thanks anyway.

**Comment by wainach** [comment]
+1

**Comment by srdante** [comment]
+1

**Comment by Paulsky** [comment]
+1 please see this comment: https://github.com/atomiclabs/cryptocurrency-icons/issues/315#issuecomment-507236516

**Comment by syeo66** [comment]
@Paulsky That comment was on 1 Jul 2019. Last commit in August... 7 months is rather a long time, especially in crypto.

**Comment by Paulsky** [comment]
Don't get me wrong, I think we are on the same page here @syeo66

**Comment by LefterisJP** [comment]
It seems this project is abandoned. I talked to Sindre and he told me he is no longer working on it.

**Comment by Paulsky** [comment]
@sindresorhus could you please start to communicate?

**Comment by syeo66** [comment]
So, I just think a project with over 250 depending repositories should find a new way to be maintained. Does anyone have ideas about how to move forward from here?

**Comment by lukechilds** [comment]
Hi guys, sorry for lack of communication, me and @sindresorhus have both moved on to other projects and don't really have time to maintain this any more.

Happy to transfer this project to a new maintainer, I'll open a new issue for this.

**Comment by lukechilds** [comment]
Leave a comment over here if you're interested in maintaining this: https://github.com/atomiclabs/cryptocurrency-icons/issues/371
