### ISSUE TITLE
Alt Coin Recommendation

### ISSUE THREAD

**Issue by Sandburg** [atomiclabs/cryptocurrency-icons#99]
Hey, 
I would appreciate, if you'd add the following coins:

KekCoin (https://kekcoin.co/)
OKcash (http://okcash.io/),
Bitsend (https://bitsend.info/),
Shift (https://www.shiftnrg.org/),
BitsShares (https://bitshares.org/),
BlackCoin (https://blackcoin.co/),
Memetic (https://memetic.ai/)

Thanks in advance

**Comment by sindresorhus** [comment]
@Sandburg We could use some help finding the logos for these coins. We need a SVG [vector version](https://en.m.wikipedia.org/wiki/Vector_graphics) of the logo. Not PNG.

**Comment by sindresorhus** [comment]
I've split this issue into separate issues per coin:

https://github.com/atomiclabs/cryptocurrency-icons/issues/155
https://github.com/atomiclabs/cryptocurrency-icons/issues/156
https://github.com/atomiclabs/cryptocurrency-icons/issues/157
https://github.com/atomiclabs/cryptocurrency-icons/issues/158
https://github.com/atomiclabs/cryptocurrency-icons/issues/159
https://github.com/atomiclabs/cryptocurrency-icons/issues/160

We already have BlackCoin: https://github.com/atomiclabs/cryptocurrency-icons/blob/master/128/color/blk.png
